# Generated by Django 6.0.3 on 2026-04-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('BCI', 'Banco BCI'), ('SANT', 'Banco Santander'), ('ESTD', 'Banco Estado'), ('CHIL', 'Banco de Chile'), ('MERC', 'Mercado Pago'), ('MACH', 'MACH (Bci)'), ('TENP', 'Tenpo'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT', 'Tether (USDT)')], default='BCI', max_length=10),
        ),
    ]
